import type { Metadata } from "next"
import "@worldcoin/mini-apps-ui-kit-react/styles.css"
import "./globals.css"

import { Inter } from "next/font/google"
import { verifySiweMessage } from "@worldcoin/minikit-js"
import { WorldAppProvider } from "@radish-la/world-auth"

const nextFont = Inter({
  subsets: [],
  weight: ["400", "700"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${nextFont.className} ${nextFont.variable} antialiased`}
      >
        <WorldAppProvider
          appName="SonarFinance"
          withValidator={async (sess) => {
            "use server"
            return verifySiweMessage(sess.payload, sess.nonce)
          }}
        >
          {children}
        </WorldAppProvider>
      </body>
    </html>
  )
}
